apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-deployment"
  labels:
    app: "app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
        - name: "app"
          image: fastapi 
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PS_DATABASE_URL
              value: postgresql://asa_chef:asa_pwd@localhost:5432
          envFrom:
            - configMapRef:
                name: postgres-config
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "app-service"
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: "app"
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: ExternalName
  externalName: localhost
